name: webrtc_flutter_poc
publish_to: 'none'
description: POC de llamada RTC (solo audio) con WebRTC y señalización por WebSocket.
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.10.5
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
